Added Navbar Fix
nss-evening-cohort-19/rare-client-blue-legs-2-electric-boogaloo pull request #33
Opened 2022-11-01 01:19 UTC by blackcl3

2022-11-01 01:21 UTC, mmccullough1997 approved these changes

2022-11-01 23:29 UTC, lesleyjkeyes requested changes
I don't think the package files should be here, should they?

2022-11-05 14:18 UTC, mmccullough1997 approved these changes

2022-11-05 14:19 UTC, lesleyjkeyes approved these changes
looks good!

2022-11-05 14:19 UTC, merged